#!/bin/bash
set -e

fun2 () { sleep 2; printf "fun2\ndone\n";      sleep 0; return 0; }
fun3 () { sleep 3; printf "fun3\ndone\n" 1>&2; sleep 0; return 0; }
fun4 () { sleep 4; printf "fun4\ndone\n";      sleep 0; return $((RANDOM%4)); }
funx () { sleep $1; printf "funx$1\ndone\n";   sleep 1; return 0; }
export -f fun2 fun3 fun4


## create non-related processes
#fun () { sleep 10; echo slow; exit 4; }
#fun & fun & fun & fun & fun &

<<REM
./plize -c 2 -vv <<.
* echo *
+ echo +
=* *
=+ +
(+ =* =+ )
.
REM

./plize -c 3 -vv <<.
a sleep 1; echo a
aa sleep 1; echo aa 1>&2 ; echo aa 1>&2
b sleep 2; echo b
c2 sleep 1; echo c2; echo c2
d sleep 1; echo d
e_ sleep 3; echo _e
=sub1 (+ b c2)
=sub2 (+ a =sub1 a)
=sub3 =sub2
=sub4 e_
(* a (+(* aa =sub1 d) e_) =sub3 =sub4)
.
echo TestDone.
